### ISSUE TITLE
Wrong exit code

### ISSUE THREAD

**Issue by pagani-BETTERHOMES** [t3n/flow-healthstatus#23]
Hi there
The exit code for success should be 0 instead of 1, otherwise the probe fails:
https://github.com/t3n/flow-healthstatus/blob/e04f95622bfbc1fea31979e7abc04a757f531f28/Classes/Command/AppCommandController.php#L156

**Comment by das-nagnag** [comment]
Thanks for your contribution, I merged the PR and tagged a new release from this – the version tag is 2.5.0 :)
